### ISSUE TITLE
It is not an issue, is just a question and the only way I found to contact you

### ISSUE THREAD

**Issue by fjae** [skenderl/Flutter-LiteMorseTrainer#1]
Hi Skenderl,

I'm fjae (Fran in real life...:D). I'm just contacting you because I'm planning to develop a similar project to yours but oriented to make it easier to communicate to deafblind people. The thing is I was planning to develop it using Google/Angular Material. In the way you have it very advanced, I'm wondering if you would like to help me with the vibration bridge in Material or if you prefer for me to dive deeper into Flutter and evolve your LiteMorse project in order to adapt it to my purpose.

Just let me know and I will do one or the other.

Anyway, I will check the way you implemented vibration plugin to evaluate if it worths to develop something alike for Material.

Just say something back and I will make a better choice with my project.

Thank you!

Cheers,
fjae

**Comment by skenderl** [comment]
Hi Fran,

I'm happy to see that you liked my work and that you trying to improve it /
make a better version of it.

The thing is i have no idea about the Angular framework (in fact i used it
once for an academic project and i didn't like it and now i don't remenber
anyhting about it), plus i think you should get to know the Flutter
framework, i know it might seem hard to understand and work with at first
but after a while you'll see it's a great framework that i think will soon
become widely used.

For now i think Flutter web is in beta, but the mobile version is stable
and ready for production use.

As for vibration i only used it to hint to the user that his input is wrong
( i used this package : https://pub.dev/packages/vibration , which you can
use to replace the 'dash' and 'dot' sound by vibrations with different
durations).

Hope this helps, cheers.
